### ISSUE TITLE
Does your bluetooth on board work fine  ?

### ISSUE THREAD

**Issue by ghost** [tunglamvghy/AsusN552VW-hackintosh#1]
I have the same laptop for ASUS N55VW. Everything goes fine but bluetooth as it repeatedly disconnects which causes that earphones can't work. What's more, I have never used Airport function because there was no contacts shown since I drived both wireless card & blutooth successfully.

> Repo: [Here](https://github.com/sirius-2/OpenCore-EFI-ASUS)
> macOS version : BigSur 11.3

**Comment by tunglamvghy** [comment]
Yes, It works very well in macOS BigSur

**Comment by ghost** [comment]
I'll have a try in my spare time. Thanks for your work !
